config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  resources :items, only: [:index, :show]
  resources :channels, only: [:index, :new, :create, :destroy]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  # URL_REGEXP = %r{(http|https)://[a-z0-9]+([\-.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(/.*)?\z}ix
  # URL_REGEXP = %r{\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z}i
  validates :link, presence: true, uniqueness: true, rss: true

  has_many :items, dependent: :destroy

  after_create :rss_worker_start

  # Starting RSS worker
  def rss_worker_start
    RssWorker.perform_async
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :channel
  validates :guid, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_action :set_channel, only: 'destroy'

  # GET /channels or /channels.json
  def index
    @channels = Channel.all
  end

  # GET /channels/new
  def new
    @channel = Channel.new
  end

  # POST /channels or /channels.json
  def create
    @channel = Channel.new(channel_params)

    respond_to do |format|
      if @channel.save
        format.html { redirect_to action: "index", notice: "Channel was successfully created." }
        format.json { render :show, status: :created, location: @channel }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1 or /channels/1.json
  def destroy
    @channel.destroy
    respond_to do |format|
      format.html { redirect_to channels_url, notice: "Channel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_channel
    @channel = Channel.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def channel_params
    params.require(:channel).permit(:link)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all.order('pub_date desc')
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/channels/_form.html.erb
<%= form_with(model: channel) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
        <% channel.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Channels</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.link %></td>
        <td><%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Channel', new_channel_path %>
<br>
<%= link_to 'Back', items_path %>

app/views/channels/new.html.erb
<h1>New Channel</h1>

<%= render 'form', channel: @channel %>

<%= link_to 'Back', channels_path %>

app/views/items/index.html.erb
<%= link_to 'RSS Channels', channels_path %>
<% @items.each do |item| %>
  <p>
    <div>
      <b><%= link_to item.title, item %></b>
    </div>
    <div>
      <%= item.pub_date.strftime('%F') %>
      at <%= item.channel.link %>
    </div>
    <div>
      <a href="<%= item.link %>">Link</a>
    </div>
  </p>
<% end %>

app/views/items/show.html.erb
<p>
<div>
  <b><%= @item.title %></b>
</div>
<div>
  <%= @item.description.html_safe %>
</div>
<div>
  <a href="<%= @item.link %>"><%= @item.link %></a>
</div>
<div>
  <br>
  <%= @item.pub_date.strftime("%F %H:%M") %>
</div>
</p>
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>